module Plushie
  class Node
    attr_reader id: String
    attr_reader type: String
    attr_reader props: Hash[Symbol, untyped]
    attr_reader children: Array[Node]

    def initialize: (id: String, type: String, ?props: Hash[Symbol, untyped], ?children: Array[Node]) -> void

    def with: (**untyped changes) -> Node
  end
end
