module Plushie
  module Type
    module Gradient
      def self.linear: ([Numeric, Numeric] from, [Numeric, Numeric] to, Array[[Numeric, String | Symbol]] stops) -> Hash[Symbol, untyped]
      def self.linear_from_angle: (Numeric angle, Array[[Numeric, String | Symbol]] stops) -> Hash[Symbol, untyped]
      def self.encode: (Hash[Symbol, untyped] value) -> Hash[Symbol, untyped]
    end
  end
end
