module Plushie
  module Type
    module LineHeight
      def self.encode: (untyped value) -> (Numeric | Hash[Symbol, Numeric] | nil)

      # module_function instance method form
      def encode: (untyped value) -> (Numeric | Hash[Symbol, Numeric] | nil)
    end
  end
end
